### ISSUE TITLE
Copy Function Definition Context Menu

### ISSUE THREAD

**Issue by namello-zmtp** [amir9480/vscode-cpp-helper#11]
Would it be possible to have a Right Click Function -> Copy Function Definition Like Visual Studio?

**Comment by amir9480** [comment]
Hello.

I don't know what that means.
Is it the coping definition to the clipboard?

**Comment by namello-zmtp** [comment]
Yes exactly! Visual Studio puts a context menu function for that when you right click a function...

**Comment by amir9480** [comment]
@namello-zmtp 
Ok, I gonna add it as soon as I can.

**Comment by amir9480** [comment]
https://github.com/amir9480/vscode-cpp-helper/commit/a9ce155f5854485157982f5777aa28f34c578434

Will be available in next update.
