### ISSUE TITLE
Do include guards properly

### ISSUE THREAD

**Issue by jdlugosz** [amir9480/vscode-cpp-helper#17]
When generating an include guard, don't use a name that's reserved for the implementation.
Mimicing what is seen in the standard headers is a common _mistake_, and one reason for using an automated tool is to always get it right.

**Comment by amir9480** [comment]
Hello.

I need more information to understand what issue is.
I'm confused now.
Please describe with code samples and your suggestion about it.

**Comment by amir9480** [comment]
@jdlugosz 
Hello.

I need more information to understand what issue is.
I'm confused now.
Please describe with code samples and your suggestion about it.

**Comment by jdlugosz** [comment]
Names containing two consecutive underscores, or beginning with an underscore followed by a capital letter, are reserved for use by the implementation.

In short, it is **exactly wrong** to imitate the guards you see in the standard library files.

Your sample animation shows the example of `__TEST_H__` which is a reserved name.  For all you know, some standard header defines a macro by that name for its own use, or worse.

**Comment by amir9480** [comment]
@jdlugosz 
You can change default config to remove underscores from header guards like this.
```
"CppHelper.HeaderGuardPattern": "{FILE}_H"
```

or
```
"CppHelper.HeaderGuardPattern": "GUARD_{FILE}_H"
```

**Comment by alexeyr** [comment]
But the default shouldn't use reserved names.
