### ISSUE TITLE
Commands not found

### ISSUE THREAD

**Issue by DnnMitko** [amir9480/vscode-cpp-helper#2]
I keep getting these notifications whenever i try to use any of the features:

command 'cpp-helper.create-header-guard' not found
command 'cpp-helper.create-implementation' not found

My settings are:

"CppHelper.HeaderGuardPattern": "`__{FILE}_H__`",
"CppHelper.SourcePattern": [
    "{FILE}.cpp",
]

I'm on VSCode version: 1.43.2

I tried reinstalling the extension, reloading the window, disable/enable of the extension and binding commands to shortcuts.
I can find the commands in the keybindings and it knows they're valid.

**Comment by amir9480** [comment]
Hello.

I need more information to find the issue.
So I need you to do these to get more information:
- Press F1 and command `Disable All Installed Extensions for this Workspace`.
- Then enable `C++ Helper` from extensions.
- Press F1 and command `Developers: Reload Window`
- After reload Go to `Help > Toggle Developer Tools` and click on the console tab.
- Right-click on your code and use `Create Implementation` or `Create Header Guard`.
- Right-click on any Error and click `Save as` and save the log file.
- Send the file here.

And also tell what OS you are using.
Thanks.

Screenshots:
![image](https://user-images.githubusercontent.com/16279288/77530782-7df8a200-6eaf-11ea-9212-a88f0b2af367.png)
![image](https://user-images.githubusercontent.com/16279288/77530853-95378f80-6eaf-11ea-8399-f94ab0f04390.png)
![image](https://user-images.githubusercontent.com/16279288/77530886-9ec0f780-6eaf-11ea-893e-26219a51bcd2.png)
![image](https://user-images.githubusercontent.com/16279288/77530923-b0a29a80-6eaf-11ea-938f-d8db0ec2b6eb.png)
![image](https://user-images.githubusercontent.com/16279288/77530942-bc8e5c80-6eaf-11ea-85cb-50ef8c739a4a.png)
![image](https://user-images.githubusercontent.com/16279288/77531179-227ae400-6eb0-11ea-976a-5b6e600ee196.png)
![image](https://user-images.githubusercontent.com/16279288/77531299-4f2efb80-6eb0-11ea-8dd6-4500a7483216.png)

**Comment by DnnMitko** [comment]
This is what I got as i opened a header, before even getting to click on a command.
Nothing new was added as i clicked on either commands.

![Spectacle J10685](https://user-images.githubusercontent.com/15691900/77532708-1554f980-6e9e-11ea-9ca8-7f99c7318bec.png)


abstractExtensionService.ts:396 Activating extension 'amiralizadeh9480.cpp-helper' failed: Cannot find module './Helpers'
Require stack:
- /home/default/.vscode/extensions/amiralizadeh9480.cpp-helper-0.0.4/out/NamespaceDetails.js
- /home/default/.vscode/extensions/amiralizadeh9480.cpp-helper-0.0.4/out/commands/CreateImplementation.js
- /home/default/.vscode/extensions/amiralizadeh9480.cpp-helper-0.0.4/out/extension.js
- /usr/share/code/resources/app/out/vs/loader.js
- /usr/share/code/resources/app/out/bootstrap-amd.js
- /usr/share/code/resources/app/out/bootstrap-fork.js.
_logMessageInConsole @ abstractExtensionService.ts:396
_logOrShowMessage @ abstractExtensionService.ts:410
$onExtensionActivationError @ mainThreadExtensionService.ts:70
_doInvokeHandler @ rpcProtocol.ts:398
_invokeHandler @ rpcProtocol.ts:383
_receiveRequest @ rpcProtocol.ts:299
_receiveOneMessage @ rpcProtocol.ts:226
(anonymous) @ rpcProtocol.ts:101
fire @ event.ts:587
fire @ ipc.net.ts:453
_receiveMessage @ ipc.net.ts:733
(anonymous) @ ipc.net.ts:592
fire @ event.ts:587
acceptChunk @ ipc.net.ts:239
(anonymous) @ ipc.net.ts:200
t @ ipc.net.ts:28
emit @ events.js:203
addChunk @ _stream_readable.js:295
readableAddChunk @ _stream_readable.js:276
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166

**Comment by amir9480** [comment]
@DnnMitko 
I think it's platform-specific problem because of file name case-sensitivity so I gonna install a Linux OS and test extension on that as soon as possible.
Thanks for your patience and help.

**Comment by amir9480** [comment]
Hello.

The issue solved in v0.0.5.
I tested on Ubuntu 18.04 and v0.0.5 works fine.
And it was a problem with compiled files on my windows.
