### ISSUE TITLE
Creating implementation sometimes doesn't work

### ISSUE THREAD

**Issue by konradglas** [amir9480/vscode-cpp-helper#20]
Hi! 
Thanks a lot for creating this! Really awesome stuff...
Sometimes I have an issue, where when I want to create an implementation, nothing happens, or the .cpp file is opened. But either way no implementation is created. Also, my cpu is getting really really busy and I cannot save the .cpp file anymore. Repoening vscode is my current solution for this.
Is there any way I can log what is going on and provide you with more details?
Thanks a lot!
Konrad

**Comment by amir9480** [comment]
@konradglas 
Hi,

Please follow this
https://github.com/amir9480/vscode-cpp-helper/issues/1#issuecomment-603793422

Also, Provide a code sample that doesn't works and tell exactly where you put your cursor.
Probably, this is an issue with the regex I used to parse codes.

**Comment by amir9480** [comment]
Please check v0.2.2 and if the issue still exists let me know.
