### ISSUE TITLE
Search by file name doesn't work in VSCode - Insiders

### ISSUE THREAD

**Issue by S0mn4mbul1st** [amir9480/vscode-cpp-helper#26]
Hi y'all, I was using the older version of vs code and while searching for any file name, it was showing me the whole files in the directory, after updating, I can see only the recently opened files. I am working in a remote workplace.

I have read other entries about the same issue and later downloaded VSCode Insiders, however, when I try to ctrl + p and search for the folder, still, I get the only recently opened files. Do you have any idea about how to fix this error?

**Comment by amir9480** [comment]
@S0mn4mbul1st 

Hi

Please put your issue here
https://github.com/microsoft/vscode
