### ISSUE TITLE
[Feature request] Create declaration from definition, with member object support

### ISSUE THREAD

**Issue by ItsCubeTime** [amir9480/vscode-cpp-helper#30]

**Comment by amir9480** [comment]
Hi there

This is a duplication of #30, So I close this issue.
Also it's not easy to implement this feature as the extension uses regex to parse code.
I still waiting for this feature in the official C++ extension.

https://github.com/microsoft/vscode-cpptools/projects/15#card-58211366

**Comment by ItsCubeTime** [comment]
I actually found my way to another similar extension to this one called "C-mantic", which handles this quite well already (tho it cant update existing definitions/declarations).
