### ISSUE TITLE
Trailing comment symbol "//"

### ISSUE THREAD

**Issue by geophysicsQC** [amir9480/vscode-cpp-helper#31]
Hi, I came across this issue when declaration is on different lines with trailing comment session, the implementation created has numerous trailing backslash "//" for those lines. Please take a look at this example:
![image](https://user-images.githubusercontent.com/24968921/116894600-dee8c280-abf7-11eb-9704-e1c607142440.png)

**Comment by geophysicsQC** [comment]
I think a good behavior for the generator should be either remove all trailing "//" or copying the original comment sessions.

**Comment by amir9480** [comment]
Hi @geophysicsQC 

As I use the [Doxygen](https://www.doxygen.nl/manual/docblocks.html) style standard for commenting methods I never faced this kind of issue
I fix this as soon as I could

**Comment by geophysicsQC** [comment]
Hi,

I usually will use Doxygen style just came across some old codes that do
this type of thing frequently. It should not be a deal breaker for me but
would be good if you can take a look.

Thanks very much!

Chen
