### ISSUE TITLE
Function not detected

### ISSUE THREAD

**Issue by qsyttkx** [amir9480/vscode-cpp-helper#35]
When I right click a member function with default value and click 'Create Implementation', I got a message: **Function not detected**.

my code:

```cpp
class ResourceModel : public QAbstractItemModel {
public:
    // Cannot impl by cpp-helper
    QModelIndex index(int row, int column, const QModelIndex& parent = QModelIndex()) const override;
    // Worked well
    QModelIndex parent(const QModelIndex& child) const override;
};
```

**Comment by Ares9323** [comment]
The error is caused by the function called as parameter, probably it's not recognized by the extension syntax

**Comment by amir9480** [comment]
Please update C++ Helper to v0.3.0

**Comment by phoenixwxy** [comment]
> Please update C++ Helper to v0.3.0

this issue is broken in v0.3.2
