### ISSUE TITLE
[[nodiscard]] attribute support

### ISSUE THREAD

**Issue by armandas** [amir9480/vscode-cpp-helper#39]
First of all, thank you for this extension, I just started using and already love it!

I have found one issue: if a `[[nodiscard]]` attribute is present in the function declaration, part of it appears in the implementation output.

Header file:

```cpp
#ifndef TEST_H
#define TEST_H

class Test
{
public:

    [[nodiscard]] bool test() const;
};

#endif // TEST_H
```

Implementation output:

```cpp
nodiscard]] bool Test::test() const
{
    
}
```

Expected output:

```cpp
bool Test::test() const
{
    
}
```

**Comment by amir9480** [comment]
@armandas 
Please update to v0.3.0
