### ISSUE TITLE
Regex match C++

### ISSUE THREAD

**Issue by 1045020768** [amir9480/vscode-cpp-helper#4]

**Comment by 1045020768** [comment]
return type with :: operator can not matched, and declaration like "int& func();" can be matched, but "int &func();" can not be matched.

**Comment by amir9480** [comment]
Hello.
Thanks for using C++ Helper.

I gonna fix this bug as soon as I can.

**Comment by amir9480** [comment]
Check v0.0.6 and if still bug exists please let me know.
