### ISSUE TITLE
Create Implementation leaves trailing space on signature of implementation

### ISSUE THREAD

**Issue by kipyminyman** [amir9480/vscode-cpp-helper#47]
Generated implementations look like
```
void Foo::testFunc() // there is a space here (bad)
{
	
}
```
when they should look like
```
void Foo::testFunc()// there is no space here (good)
{
	
}
```

**Comment by amir9480** [comment]
Fixed and next version will released soon

With this setting, all my source codes always don't have trailing space, and never noticed this issue.
```json
"files.trimTrailingWhitespace": true,
```
