### ISSUE TITLE
No License information

### ISSUE THREAD

**Issue by SjurWarEagle** [amir9480/vscode-cpp-helper#6]
The project is missing any kind of licensing, this means it cannot be used in areas where you have to have permission to use a software (like commerically).

**Comment by amir9480** [comment]
Hello.

Thanks for using C++ Helper.
I created License File.
This project's source license is MIT.
You are free to use it anywhere for any purpose.

https://github.com/amir9480/vscode-cpp-helper/blob/master/LICENSE.md
