### ISSUE TITLE
Template implementation within header file

### ISSUE THREAD

**Issue by geophysicsQC** [amir9480/vscode-cpp-helper#7]
(Update): I found that I could do that by adding the {FILE}.hpp in my settings file. So this should not be an issue now...

Could we add a feature to implement the template within the same header file? Thanks.

**Comment by amir9480** [comment]
If extension not found any source file with header name then implementation will be added in the same file underclass

Also, it's best practice to use `.inl` files for template classes.

header.h:
```cpp
template<typename T>
class Test
{
// ...
};
#include "source.inl"
```
---
source.inl:
```cpp
#include "header.h"

//...
```

**Comment by amir9480** [comment]
Please update to version 0.1.0 and there is a new item `Create Implementation Here` in the context menu.
